#! /usr/bin/env sh

####################
# DO NOT EDIT THIS FILE
# PLEASE ENSURE YOU UNDERSTAND ITS PURPOSE AND ORIGIN BEFORE EDITING.

# This should only be run the firt time you setup a new environment.

# This file has been copied directly from
#   https://github.com/olmesm/terraform/state-lock
####################

TF_REMOTE_STATE_FILE="remote_state.tf"

if [ -f "$TF_REMOTE_STATE_FILE" ]; then
  echo "
\"$TF_REMOTE_STATE_FILE\" already exists.

This script should only be run
when first setting up your state bucket.

Please see the README.md for more info
"
  exit 1
fi

# Clean
rm -rf .terraform

# Init
terraform init -reconfigure

# Create the lock DB
terraform apply -target module.aws_dynamodb_table.dynamodb_state_lock -auto-approve

# Create the bucket
terraform apply -target module.aws_s3_bucket.state_bucket -auto-approve

# Make the remote state file
terraform apply -target module.local_file.remote_state -lock=false -auto-approve

# Copy state up
terraform init -force-copy
